### ISSUE TITLE
Crash while autocrafting with arcane terminal

### ISSUE THREAD

**Issue by Sagenseele** [Delfayne/ThaumicEnergistics#39]
**Steps to Reproduce**
1. Setup an rudimentary AE System with arcane assembler and knowledge core
2. Go into an arcane terminal/arcane inscriber
3. Click "Craft" item via arcane assembler
4. Select "Next" in the "amount" screen
5. Soft Crash

Error CastException:
java.lang.ClassCastException: thaumicenergistics.client.gui.crafting.GuiCraftAmountBridge cannot be cast to thaumicenergistics.mixin.ae2.CraftAmountAccessor

**Expected behavior**
The screen with the summary of the crafting should be visible to confirm the auto-craft.

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2860
 - Applied Energistics: ae2-uel-v0.56.4
 - Thaumcraft: Thaumcraft-1.12.2-6.1.BETA26.
 - Thaumic Energistics: thaumic-energistics-extended-life-1.12.2-2.3.0.jar
 - Modpack: 1.12.2

**Additional context**
Related to #36 and the release of v2.3.0 and maybe in the broadest context: https://github.com/AE2-UEL/Applied-Energistics-2/issues/418

**Logs/Crashlogs**
Crash Report: https://pastebin.com/gfVRcWji

I appreciate your work and I am thankful for your contribution to the minecraft community.

**Comment by Delfayne** [comment]
Already fixed in the development release hosted on Github

**Comment by Sagenseele** [comment]
Hello, in which arrangement do I have to use the v2.3.0-dev.jar? I tried to throw it in the mods folder with the other mods, but unfortunately I can't start the game with any combination of dev.jar/api.jar/sources.jar. Only the 2.3.0 Release jar works, but I still get the CastExceptionError.

Using the same mods as before:

- ae2-uel-v0.56.4.jar
- Baubles-1.5.2
- thaumcraft1.12.6-6.1.BETA26

**Comment by Delfayne** [comment]
only the untagged jar, you don't need dev or api or anything.

I've heard reports that the release I've posted here is not currently working, so I need to double check everything. If you gain more information from trying this version, it would be appreciated

**Comment by Sagenseele** [comment]
I would like to test the build, but I'm too unexperienced to get it to work. I try building the .jar and am stuck at this part. I will tell you, what I see in the crash-logs and ingame as soon as I learn how to build gradle projects.
